spring:
  datasource:
    password: password
    url: jdbc:mysql://localhost:33306/kitchenpos
    username: user
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
